# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [30]:
import numpy as np
arr1=np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
print(arr1)
arr1.reshape(2,5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [7]:
arr2=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr3=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])             
np.vstack((arr2,arr3))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [9]:
arr2=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
arr3=np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.hstack((arr2,arr3))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [19]:
arr4=np.arange(0,10)
print(arr4.reshape(2,5))
arr4.flatten()


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [23]:
arr5=np.arange(0,15)
print(arr5.reshape(1,3,5))
arr5.ravel()

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [27]:
arr6=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
print(arr6)
arr6.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [27]:
a=np.arange(25)
a1=a.reshape(5,5)
print(a1)
np.square(a1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [29]:
b=np.arange(1,31)
c=b.reshape(5,6)
print(c)
c.mean()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [32]:
c.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [34]:
np.median(c)

15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
print(c)
c.transpose()

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [45]:
d=np.arange(5,36,2)
d1=d.reshape(4,4)
print(d1)
d1.trace()

[[ 5  7  9 11]
 [13 15 17 19]
 [21 23 25 27]
 [29 31 33 35]]


80

## Question:13

### Find the determinant of the previous array in Q12?

In [50]:
np.linalg.det(d1)

-7.573064690121646e-29

## Question:14

### Find the 5th and 95th percentile of an array?

In [37]:
arr7=np.random.randint(100,size=(6,6))
print(arr7)
a=np.percentile(arr7,5)
print("this is 5th percentile =",a)
b=np.percentile(arr7,95)
print("this is 95th percentile =",b)

[[73 27 20 54 98 44]
 [ 3 16 59 37 33 77]
 [ 2 99 68 27 60 56]
 [81 47 82 18 32 66]
 [70 35 89  5 65 61]
 [ 8 25 78 84 44 20]]
this is 5th percentile = 4.5
this is 95th percentile = 91.25


## Question:15

### How to find if a given array has any null values?

In [39]:
arr8=np.array([[0,15,4,1,0,8,8,0],[2,5.5,6,8,0,1,0,4]])
print(arr8)
arr8==0

[[ 0.  15.   4.   1.   0.   8.   8.   0. ]
 [ 2.   5.5  6.   8.   0.   1.   0.   4. ]]


array([[ True, False, False, False,  True, False, False,  True],
       [False, False, False, False,  True, False,  True, False]])